Repository crystal-lang/crystal-book, pull requests merged in 2022-01, with the labels that each got.

#573 Delete reference to missing script.js
  mkdocs.yml
Labels: bug

#562 Use the version of Crystal according to the current branch
  .github/workflows/deploy-book.yml
  hooks.py
Labels: enhancement, site-generator

#582 Add `netlify.toml`
  netlify.toml
Labels: enhancement
