Repository crystal-lang/crystal-book, pull requests merged in 2024-04, with the labels that each got.

#753 Add documentation entry for `crystal tool flags`
  docs/man/crystal/README.md
Labels: enhancement

#752 Reorganize compile time flags for the compiler
  docs/syntax_and_semantics/compile_time_flags.md
Labels: enhancement

#754 Merge `release/1.11`
  docs/README.md
  docs/SUMMARY.md
  docs/syntax_and_semantics/select.md
Labels: infrastructure

#755 Upgrade dependencies
  docs/syntax_and_semantics/documenting_code.md
  mkdocs.yml
  requirements.in
  requirements.txt
Labels: dependencies

#757 Update `devenv.lock`
  devenv.lock
Labels: infrastructure

#758 Add reference to compiler manual in Testing Guide
  docs/guides/testing.md
Labels: enhancement

#759 Update spec parameters
  docs/man/crystal/README.md
Labels: enhancement

#746 Document `asm`
  devenv.lock
  docs/SUMMARY.md
  docs/syntax_and_semantics/asm.md
  docs/syntax_and_semantics/documenting_code.md
  mkdocs.yml
  requirements.in
  requirements.txt
Labels: enhancement
