Repository crystal-lang/crystal-book, pull requests merged in 2024-01, with the labels that each got.

#730 Add new unreachable options to compiler manual
  docs/man/crystal/README.md
Labels: enhancement

#729 Add optimization levels to compiler manual
  docs/man/crystal/README.md
  docs/syntax_and_semantics/compile_time_flags.md
Labels: enhancement

#731 Update options for `crystal spec`
  docs/man/crystal/README.md
Labels: enhancement

#728 Document `alignof` and `instance_alignof`
  docs/SUMMARY.md
  docs/syntax_and_semantics/alignof.md
  docs/syntax_and_semantics/instance_alignof.md
Labels: enhancement

#733 Add links to `alignof` and `instance_alignof`
  docs/syntax_and_semantics/type_grammar.md
Labels: enhancement

#739 Run `deploy config` workflow only when a release branch is created
  .github/workflows/deploy-config.yml
Labels: infrastructure

#741 Add example of accessing class method from instance method
  docs/syntax_and_semantics/class_methods.md
Labels: enhancement

#743 Fix `deploy-config.yml` workflow
  .github/workflows/deploy-config.yml
Labels: bug

#725 Mention argless `#annotations` method in annotation docs
  docs/syntax_and_semantics/annotations/README.md
Labels: enhancement
