Repository crystal-lang/crystal-book, pull requests merged in 2025-05, with the labels that each got.

#830 Fix typos
  docs/guides/hosting/gitlab.md
  docs/project/release-policy.md
  docs/syntax_and_semantics/annotations/README.md
  docs/syntax_and_semantics/literals/string.md
  docs/syntax_and_semantics/operators.md
  docs/syntax_and_semantics/platform_support.md
Labels: bug

#831 Change link in logo to Crystal homepage
  mkdocs.yml
Labels: enhancement

#832 Change nav link label from _Welcome_ to _Index_
  docs/SUMMARY.md
Labels: enhancement

#834 devenv update
  devenv.lock
Labels: infrastructure

#833 [CI] Add pre-commit lint workflow
  .github/workflows/lint.yml
Labels: infrastructure
