Repository crystal-lang/crystal-book, pull requests merged in 2025-04, with the labels that each got.

#818 Update documentation for `--output` option
  docs/man/crystal/README.md
Labels: enhancement

#819 Bump support for LLVM 20
  docs/man/required_libraries.md
Labels: enhancement

#822 Document `CRYSTAL_EXEC_PATH`
  docs/man/crystal/README.md
Labels: enhancement

#823 Document macro versions of `sizeof` and `alignof`
  docs/syntax_and_semantics/alignof.md
  docs/syntax_and_semantics/sizeof.md
Labels: enhancement

#821 Add latest versions of libraries from repology
  docs/man/required_libraries.md
Labels: enhancement

#824 Add documentation for `:showdoc:`
  docs/syntax_and_semantics/documenting_code.md
Labels: enhancement

#825 Fix DB transactions guide
  docs/database/transactions.md
Labels: bug

#827 Add warning about Apple's libxml
  docs/man/required_libraries.md
Labels: enhancement

#829 Merge `release/1.15` into `master`
  docs/man/required_libraries.md
  docs/syntax_and_semantics/enum.md
  docs/syntax_and_semantics/operators.md
Labels: kind:chore
